### ISSUE TITLE
Add method to directly add tasks/mixtures.

### ISSUE THREAD

**Issue by salayatana66** [google/seqio#215]
Currently `MixtureRegistry` and `TaskRegistry` have an `add` method that takes the arguments to construct a `Mixture` /  `Task`. This does not seem to play well if one wants to subclass `Mixture` or `Task` with a class that takes different arguments and add them to the registries. Concrete example of a subclass of `Task`: turning a `Mixture` back into a task so that it looks "atomic" when one tries to add it back into a `Mixture`. Would it be possible to have a method to add to the Registrie(s) directly an object, without having to pass
the arguments that the constructor uses?

**Comment by gauravmishra** [comment]
Hi, both TaskRegistry and MixtureRegistry support this through "add_provider", e.g.
my_task = MyTaskSubclass(...)
seqio.TaskRegistry.add_provider("my_task_name", my_task)

Let me know if you run into any issues. Thanks!
