### ISSUE TITLE
Tokenizer is not behaving as expected on special tokens (doesn't recognize `pad` and `eos` tokens)

### ISSUE THREAD

**Issue by armancohan** [google/seqio#311]
Looks like tokens like `eos` and `pad` do not get tokenized correctly:

Repro:
```python
In [1]: import seqio

In [2]: vocab = seqio.SentencePieceVocabulary('gs://t5-data/vocabs/cc_all.32000/sentencepiece.model')

In [3]: vocab.tokenizer.id_to_piece(0)
Out[3]: '<pad>'

In [4]: vocab.tokenizer.id_to_piece(1)
Out[4]: '</s>'

In [5]: vocab.encode(vocab.tokenizer.id_to_piece(1))
Out[5]: [3, 2, 87, 7, 3155]

In [6]: vocab.tokenizer.id_to_piece(vocab.tokenizer.encode(vocab.tokenizer.id_to_piece(1)))
Out[6]: ['▁', '<unk>', '/', 's', '>']
```

It breaks down the special tokens into wordpieces.

**Comment by gauravmishra** [comment]
Hi @armancohan, this is working as expected. eos, pad, etc. are special ids (with corresponding labels for human readability) and are used after encoding to denote special meaning, e.g. <unk> denotes that a given piece of text was not found in the vocab, so if "armancohan" isn't in the vocab, running decode(encode("armancohan")) will give you '<unk>'. But, these labels themselves may or may not be in the vocab, e.g. encode("<unk>") may map to 87 denoting that it wasn't found in the vocab, or to one or more vocab ids if it belongs to the vocab. Similarly, 1 is appended at the end of ids to denote end of sequence and has a label "</s>" to make it human readable, but actually encoding "</s>" won't (and shouldn't) return the eos id.
