### ISSUE TITLE
seqio 0.0.13 cannot be installed on Apple Silicon due to transitive tensorflow dependency of clu

### ISSUE THREAD

**Issue by tuzhucheng** [google/seqio#396]
https://github.com/google/seqio/commit/db4d4b05de7e7151bc2b4a8310f5a7e040f528c1 added `clu` as a dependency of `seqio`.

With this change, we can no longer install `seqio` on Apple Silicon machines (e.g. M1, M2). This is because `clu` requires `tensorflow` (https://github.com/google/CommonLoopUtils/blob/85f9d28556f2684e2c5f2e412cbef5119d6682ba/setup.py#L54) but on Apple Silicon `tensorflow` should be installed as `tensorflow-macos` based on the instructions at https://developer.apple.com/metal/tensorflow-plugin/.

A simple fix is to update the `clu` `tensorflow` line in the setup.py to `tensorflow; platform_machine == 'x86_64'`. However, that project doesn't accept GitHub issues or contributions so I am creating an issue here.

**Comment by adarob** [comment]
@Marvin182 fyi

**Comment by Marvin182** [comment]
Thanks. github.com/google/CommonLoopUtils/pull/250 should fix it
