### ISSUE TITLE
Different preprocessors for each dataset split

### ISSUE THREAD

**Issue by marcospiau** [google/seqio#407]
Hi,

I'm working on an STS task and using a `seqio.TfdsDataSource`  task and [`t5.data.preprocessors.stsb`](https://github.com/google-research/text-to-text-transfer-transformer/blob/9060eb08a0198c8d73f3b691252fddc16268a705/t5/data/preprocessors.py#L816) as preprocessor. After seeing some generated examples I realize that both training and eval data are preprocessed, so metrics calculated on test split use a processed version of the target instead of the original values. Using  `t5.data.preprocessors.stsb` as example, during training a label value of 3.25 is converted to "3.2"; during eval steps, I'd like to just convert this value to float without rounding ("3.25").

Is there a way to apply different preprocessors for each dataset split? It would be ideal for the evaluation metrics functions to consume gold labels as close as possible to the original values. The [postprocessing section](https://github.com/google/seqio#postprocessor) on README  mentions `is_target` argument for postprocessing functions, but I could't find a similar instruction for preprocessor functions.

Thanks,
Marcos

**Comment by adarob** [comment]
You can create different tasks for each split and then put them in to the same mixture, which will achieve the same result.

**Comment by marcospiau** [comment]
Thanks, @adarob!
